# Generated by Django 3.2.23 on 2024-01-19 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='category')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vitamins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='vitamins')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=70)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='products')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('calories', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=None)),
                ('weight', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.category')),
                ('diet', models.ManyToManyField(to='model.Diet')),
                ('vitamins', models.ManyToManyField(to='model.Vitamins')),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.user'),
        ),
    ]
