# Generated by Django 3.2.23 on 2024-01-19 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=70)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.gender')),
            ],
        ),
    ]
